name: Build DLL and Upload Artifacts

on:
  push:
    branches: [ main ] # mainブランチへのプッシュ時に実行 (適宜変更してください)
  pull_request:
    branches: [ main ] # mainブランチへのプルリクエスト時に実行 (適宜変更してください)

jobs:
  build:
    runs-on: ubuntu-latest # ビルドを実行する環境 (windows-latestなども選択可能)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.*' # プロジェクトに必要な.NETのバージョン

    - name: Restore dependencies
      run: dotnet restore vrc-oscquery-lib.sln # ソリューションファイル名を指定

    - name: Build in Release mode
      run: dotnet build --configuration Release --no-restore vrc-oscquery-lib.sln # ソリューションファイル名を指定

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vrc-oscquery-lib-release-artifacts # アップロードされるアーティファクト名
        path: | # アップロードするファイルのパス (複数指定可能)
          vrc-oscquery-lib/bin/Release/net462/*.*
        if-no-files-found: error # 対象ファイルが見つからない場合にエラーにする